# Post Service Local Development Environment
# Docker Compose로 로컬 개발 환경 구성 (SQLite 버전)

services:
  # Post 서비스 (Flask 애플리케이션)
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - ENVIRONMENT=development
      - USER_SERVICE_URL=http://localhost:8081
      - NOTIFICATION_SERVICE_URL=http://localhost:8082
      - FLASK_APP=app.py
      - FLASK_ENV=development
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    restart: unless-stopped
    networks:
      - post-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  post-network:
    driver: bridge


